import OpenAI from "openai";
import { imagekit } from "../../lib/imagekit";
import * as fs from "fs";
import * as path from "path";
import sharp from "sharp";

/* ======================================================
   JERSEY IMAGE GENERATION SERVICE
   Using OpenAI DALL-E 3 / GPT-4 Vision for high-quality jersey designs
   With Preset Instructions, Source File Support, and Prompt Cache
====================================================== */

/* -------------------------------------------------------
   PROMPT CACHE - stores last 2 successful DALL-E prompts
   so similar inputs reuse a proven design spec
------------------------------------------------------- */
interface CachedPrompt {
  cacheKey: string;        // hash of user input params
  designSpec: string;      // the detailed design spec generated by GPT-4
  dallePromptBase: string; // compact base prompt used for DALL-E
  timestamp: number;
}

const promptCache: CachedPrompt[] = []; // max 2 entries

function makeCacheKey(options: GenerateJerseyOptions): string {
  const { prompt, preset, playerName, playerNumber, teamName, customInstructions } = options;
  return [prompt, preset, playerName, playerNumber, teamName, customInstructions]
    .map(v => (v || "").toLowerCase().trim())
    .join("|");
}

function getCachedPrompt(options: GenerateJerseyOptions): CachedPrompt | null {
  const key = makeCacheKey(options);
  return promptCache.find(c => c.cacheKey === key) || null;
}

function saveToCache(options: GenerateJerseyOptions, designSpec: string, dallePromptBase: string) {
  const key = makeCacheKey(options);
  // Remove existing entry for same key if present
  const idx = promptCache.findIndex(c => c.cacheKey === key);
  if (idx !== -1) promptCache.splice(idx, 1);
  // Keep max 2 entries
  if (promptCache.length >= 2) promptCache.shift();
  promptCache.push({ cacheKey: key, designSpec, dallePromptBase, timestamp: Date.now() });
  console.log(`[Prompt Cache] Saved. Cache size: ${promptCache.length}`);
}

/* -------------------------------------------------------
   JERSEY MASK LOADER - reads front/back mask files and
   converts them to base64 for GPT-4 Vision reference
------------------------------------------------------- */
function loadMaskAsBase64(maskRelPath: string): string | null {
  try {
    // Resolve from backend root -> frontend/public
    const fullPath = path.resolve(__dirname, "../../../../frontend/public", maskRelPath);
    if (!fs.existsSync(fullPath)) {
      console.warn(`[Mask Loader] File not found: ${fullPath}`);
      return null;
    }
    const buf = fs.readFileSync(fullPath);
    return buf.toString("base64");
  } catch (e) {
    console.warn("[Mask Loader] Error loading mask:", e);
    return null;
  }
}

// Preset Design Templates
export const JERSEY_PRESETS = {
  classic: {
    name: "Classic Striped",
    description: "Traditional vertical stripes design",
    style: "Classic football jersey with vertical stripes",
    collar: "V-neck",
    fabric: "Breathable mesh",
    pattern: "Vertical stripes",
    instructions: "Create a classic football jersey with clean vertical stripes. Traditional design suitable for established clubs. Use bold contrasting colors."
  },
  modern: {
    name: "Modern Minimal",
    description: "Clean, minimal contemporary design",
    style: "Modern minimal with geometric accents",
    collar: "Crew neck",
    fabric: "Matte performance fabric",
    pattern: "Minimal with subtle geometric patterns",
    instructions: "Design a sleek, modern jersey with minimal elements. Use geometric patterns subtly. Focus on clean lines and contemporary aesthetics."
  },
  aggressive: {
    name: "Aggressive Sport",
    description: "Bold, dynamic design for competitive teams",
    style: "Aggressive with sharp angular patterns",
    collar: "V-neck with contrast trim",
    fabric: "Glossy athletic fabric",
    pattern: "Angular geometric patterns",
    instructions: "Create an aggressive, dynamic jersey design with sharp angles and bold patterns. Suitable for competitive teams. Use strong contrasting elements."
  },
  retro: {
    name: "Retro Vintage",
    description: "Nostalgic old-school football style",
    style: "Retro vintage with classic elements",
    collar: "Polo collar",
    fabric: "Textured cotton-like fabric",
    pattern: "Horizontal stripes or solid with retro details",
    instructions: "Design a retro-inspired jersey reminiscent of 70s-90s football. Use vintage color palettes and classic design elements."
  },
  gradient: {
    name: "Gradient Fade",
    description: "Modern gradient color transitions",
    style: "Modern gradient fade design",
    collar: "Round neck",
    fabric: "Smooth performance fabric",
    pattern: "Gradient color transitions",
    instructions: "Create a jersey with smooth gradient color transitions. Modern aesthetic with flowing color blends from top to bottom or center outward."
  },
  camo: {
    name: "Camo Tactical",
    description: "Camouflage inspired tactical design",
    style: "Tactical camo pattern",
    collar: "Crew neck",
    fabric: "Durable athletic fabric",
    pattern: "Camouflage or tactical pattern",
    instructions: "Design a tactical-inspired jersey with camo patterns or military-inspired elements. Rugged, durable appearance."
  },
  neon: {
    name: "Neon Electric",
    description: "Bright neon colors for visibility",
    style: "Electric neon with high visibility",
    collar: "V-neck",
    fabric: "Shiny synthetic fabric",
    pattern: "Neon accents and electric patterns",
    instructions: "Create a high-visibility jersey with neon colors and electric accents. Bold, eye-catching design for maximum impact."
  },
  marble: {
    name: "Marble Luxury",
    description: "Elegant marble texture design",
    style: "Luxury marble texture",
    collar: "Round neck with gold/silver trim",
    fabric: "Premium smooth fabric",
    pattern: "Marble or stone texture patterns",
    instructions: "Design an elegant jersey with marble or stone-like textures. Luxury aesthetic with sophisticated color combinations."
  }
} as const;

export type JerseyPresetKey = keyof typeof JERSEY_PRESETS;

const BASE_SYSTEM_PROMPT = `
You are a professional sports apparel designer and advanced AI image generator specializing in football jerseys.

Your task is to generate exactly two ultra-realistic, high-resolution images of a football jersey based strictly on the user's design requirements.

IMAGE REQUIREMENTS:

Image 1: Front view of the football jersey
Image 2: Back view of the football jersey

DESIGN RULES:

- Follow the user's instructions for colors, patterns, logos, text, name, and number precisely
- Ensure perfect design consistency between front and back (same fabric, colors, and patterns)
- Jersey must look professionally manufactured, suitable for real match play
- Use clean stitching, realistic fabric folds, and accurate textures

JERSEY PRESENTATION - CRITICAL MOCKUP STYLE:

- FLAT-LAY PRODUCT MOCKUP STYLE - display jersey laid flat from directly above
- PURE WHITE BACKGROUND (#FFFFFF) - completely clean, no gradients, no shadows on background
- NO MANNEQUIN, NO HUMAN MODEL - just the jersey itself
- Center the jersey clearly in the frame with even margins
- Clean, professional e-commerce product photography style
- No watermarks, no extra text, no background objects, no studio props
- Even, diffused lighting without harsh shadows

FRONT VIEW (Image 1 must show):

- Primary and secondary colors clearly visible
- Collar type (round, V-neck, polo, crew neck, etc.)
- Sleeve design and patterns exactly as specified
- Team logo placement on chest (if provided)
- Sponsor text or logo (if provided)
- Any side panels or special design elements

BACK VIEW (Image 2 must show):

- Player name clearly printed in bold font at top
- Jersey number in large, bold, readable font centered below name
- Back panel or side design elements matching front
- Same fabric and color alignment as front view
- All back details exactly as specified

QUALITY STANDARDS:

- High sharpness and clarity
- Professional sports apparel quality
- Realistic fabric texture and material appearance
- Perfect consistency between both images
- Clean edges suitable for product mockup use

CRITICAL REQUIREMENTS:

- Generate EXACTLY 2 images - no more, no fewer
- Both images must show the SAME jersey design from different angles
- PURE WHITE BACKGROUND is mandatory - no exceptions
- Flat-lay presentation from directly above
- Suitable for professional product mockups and e-commerce
`;

interface GenerateJerseyOptions {
  prompt: string;
  customInstructions?: string;
  preset?: JerseyPresetKey;
  sourceFiles?: string[]; // Array of base64 encoded reference images
  playerName?: string;
  playerNumber?: string;
  teamName?: string;
}

interface JerseyGenerationResult {
  success: boolean;
  images: string[];
  prompt: string;
  model: string;
  preset?: string | null;
  sourceFilesAnalyzed?: number;
  fromCache?: boolean;
}

/**
 * Build a short user-readable spec for GPT-4 analysis
 */
function buildEnhancedPrompt(options: GenerateJerseyOptions): string {
  const { prompt, customInstructions, preset, playerName, playerNumber, teamName } = options;
  let presetLine = "";
  if (preset && JERSEY_PRESETS[preset]) {
    const p = JERSEY_PRESETS[preset];
    presetLine = ` | Preset: ${p.name} - ${p.style}, collar: ${p.collar}, fabric: ${p.fabric}, pattern: ${p.pattern}`;
  }
  const parts: string[] = [];
  if (playerName) parts.push(`Player: ${playerName}`);
  if (playerNumber) parts.push(`Number: ${playerNumber}`);
  if (teamName) parts.push(`Team: ${teamName}`);
  return `${prompt}${presetLine}${parts.length ? " | " + parts.join(", ") : ""}${customInstructions ? " | " + customInstructions : ""}`;
}

/**
 * Build compact DALL-E base prompt (hard capped at 3400 chars)
 */
function buildDallEPromptBase(options: GenerateJerseyOptions): string {
  const { prompt, customInstructions, preset, playerName, playerNumber, teamName } = options;
  const parts: string[] = [];
  if (playerName) parts.push(`Player: ${playerName}`);
  if (playerNumber) parts.push(`Number: ${playerNumber}`);
  if (teamName) parts.push(`Team: ${teamName}`);
  let presetLine = "";
  if (preset && JERSEY_PRESETS[preset]) {
    const p = JERSEY_PRESETS[preset];
    presetLine = `\nStyle: ${p.style}. Collar: ${p.collar}. Pattern: ${p.pattern}.`;
  }
  let core = `Photorealistic football jersey. Flat-lay on pure white background. No human, no mannequin. Product mockup.\nDESIGN: ${prompt}${presetLine}`;
  if (parts.length) core += `\n${parts.join(", ")}`;
  if (customInstructions) core += `\n${customInstructions.slice(0, 150)}`;
  return core.slice(0, 3400);
}

/**
 * Step 0: Generate a single unified design spec via GPT-4 Vision.
 * Uses jersey mask templates as shape reference + user source images.
 * Returns a compact spec (~400 chars) shared between front and back DALL-E prompts.
 */
async function generateUnifiedDesignSpec(
  openai: OpenAI,
  options: GenerateJerseyOptions,
  maskFrontBase64: string | null,
  maskBackBase64: string | null,
  sourceAnalysis: string,
  maskLeftBase64?: string | null,
  maskRightBase64?: string | null
): Promise<string> {
  const userDesc = buildEnhancedPrompt(options);
  const imageContents: any[] = [];
  if (maskFrontBase64) {
    imageContents.push({ type: "image_url", image_url: { url: `data:image/webp;base64,${maskFrontBase64}`, detail: "low" } });
  }
  if (maskBackBase64) {
    imageContents.push({ type: "image_url", image_url: { url: `data:image/webp;base64,${maskBackBase64}`, detail: "low" } });
  }
  if (maskLeftBase64) {
    imageContents.push({ type: "image_url", image_url: { url: `data:image/webp;base64,${maskLeftBase64}`, detail: "low" } });
  }
  if (maskRightBase64) {
    imageContents.push({ type: "image_url", image_url: { url: `data:image/webp;base64,${maskRightBase64}`, detail: "low" } });
  }
  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
        {
          role: "system",
          content: "You are a football jersey design expert. Given a user request and optional reference images, produce a SINGLE detailed design spec (max 500 chars) that defines: exact primary/secondary colors (use specific color names), sleeve pattern geometry (describe EXACT shapes: zigzag, chevrons, stripes, etc.), collar style, fabric texture, logo/text placement. CRITICAL: Describe sleeve patterns in detail so they can be replicated identically across all 4 views. Be precise about pattern colors and geometry. This spec ensures all views show the SAME jersey."
        },
        {
          role: "user",
          content: [
            { type: "text", text: `User request: ${userDesc}${sourceAnalysis ? `\nReference: ${sourceAnalysis.slice(0, 200)}` : ""}\n\nOutput unified design spec:` },
            ...imageContents
          ]
        }
      ],
      max_tokens: 200
    });
    const spec = response.choices[0]?.message?.content?.trim() || "";
    return spec.slice(0, 500) || userDesc.slice(0, 500);
  } catch (e) {
    console.warn("[Design Spec] GPT-4 failed, using user prompt:", e);
    return userDesc.slice(0, 400);
  }
}

/**
 * Analyze source/reference images using GPT-4 Vision
 * Returns design insights based on reference images
 */
async function analyzeSourceImages(
  openai: OpenAI,
  sourceFiles: string[]
): Promise<string> {
  if (!sourceFiles || sourceFiles.length === 0) {
    return "";
  }

  try {
    const imageContents = sourceFiles.map(base64 => ({
      type: "image_url" as const,
      image_url: {
        url: `data:image/png;base64,${base64}`,
        detail: "high" as const
      }
    }));

    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
        {
          role: "system",
          content: `You are a design analysis expert. Analyze the provided reference images and extract key design elements that should be incorporated into a football jersey design. Focus on:
- Color schemes and palettes
- Patterns and textures
- Design style (modern, classic, aggressive, minimal, etc.)
- Any unique visual elements
- Overall aesthetic and mood

Provide a concise summary of design recommendations based on these reference images.`
        },
        {
          role: "user",
          content: [
            {
              type: "text",
              text: "Analyze these reference images and provide design recommendations for a football jersey:"
            },
            ...imageContents
          ]
        }
      ],
      max_tokens: 500
    });

    const analysis = response.choices[0]?.message?.content || "";
    return analysis ? `\n\nREFERENCE IMAGE ANALYSIS:\n${analysis}\nIncorporate these design elements into the jersey.` : "";
  } catch (error) {
    console.warn("[Source Image Analysis] Failed to analyze reference images:", error);
    return "";
  }
}

/**
 * Analyze the generated front jersey image and extract design details for consistent back view
 */
async function analyzeFrontJerseyDesign(
  openai: OpenAI,
  frontImageBase64: string
): Promise<string> {
  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
        {
          role: "system",
          content: `You are a jersey design analyzer. Analyze the front jersey image and extract EXACT design specifications.

Describe in detail:
1. Primary color and exact shade
2. Secondary/accent colors and their exact placement
3. Pattern type (stripes, geometric, gradient, solid, etc.) with precise details
4. Collar style and color
5. Sleeve design and patterns
6. Any logos, emblems, or special design elements
7. Fabric texture appearance
8. Trim and border details

Your output will be used to generate a matching back view, so be EXTREMELY specific about colors, patterns, and design elements.`
        },
        {
          role: "user",
          content: [
            {
              type: "text",
              text: "Analyze this front jersey design and provide detailed specifications for creating a matching back view:"
            },
            {
              type: "image_url",
              image_url: {
                url: `data:image/png;base64,${frontImageBase64}`,
                detail: "high"
              }
            }
          ]
        }
      ],
      max_tokens: 800
    });

    return response.choices[0]?.message?.content || "";
  } catch (error) {
    console.warn("[Front Analysis] Failed to analyze front jersey:", error);
    return "";
  }
}

/**
 * Generate jersey images using OpenAI DALL-E 3
 * Flow: check cache → load masks → GPT-4 unified design spec → DALL-E front → DALL-E back → cache save
 */
export async function generateJerseyImages(
  options: GenerateJerseyOptions
): Promise<JerseyGenerationResult> {
  const { preset, sourceFiles, playerName, playerNumber } = options;

  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    throw new Error(
      "OPENAI_API_KEY is not configured. Get a key at https://platform.openai.com/api-keys and add it to your .env file."
    );
  }

  const openai = new OpenAI({ apiKey });

  try {
    // ── Step 1: Check prompt cache ────────────────────────────────────────
    const cached = getCachedPrompt(options);
    let designSpec: string;
    let dalleBase: string;
    let fromCache = false;

    if (cached) {
      console.log(`[Jersey Generation] Cache HIT - reusing design spec`);
      designSpec = cached.designSpec;
      dalleBase = cached.dallePromptBase;
      fromCache = true;
    } else {
      // ── Step 2: Analyze user-provided source files ───────────────────────
      let sourceAnalysis = "";
      if (sourceFiles && sourceFiles.length > 0) {
        console.log(`[Jersey Generation] Analyzing ${sourceFiles.length} reference image(s)...`);
        sourceAnalysis = await analyzeSourceImages(openai, sourceFiles);
      }

      // ── Step 3: Load jersey mask templates as shape reference ─────────────
      console.log(`[Jersey Generation] Loading jersey mask templates...`);
      const maskFront = loadMaskAsBase64("masks/jersey/front.webp");
      const maskBack  = loadMaskAsBase64("masks/jersey/back.webp");
      const maskLeft  = loadMaskAsBase64("masks/jersey/left.webp");
      const maskRight = loadMaskAsBase64("masks/jersey/right.webp");
      console.log(`[Jersey Generation] Masks loaded - front: ${!!maskFront}, back: ${!!maskBack}, left: ${!!maskLeft}, right: ${!!maskRight}`);

      // ── Step 4: Generate unified design spec via GPT-4 Vision ─────────────
      console.log(`[Jersey Generation] Generating unified design spec...`);
      designSpec = await generateUnifiedDesignSpec(openai, options, maskFront, maskBack, sourceAnalysis, maskLeft, maskRight);
      console.log(`[Jersey Generation] Design spec (${designSpec.length} chars): ${designSpec.slice(0, 100)}...`);

      // Build compact prompt base (will be shared for front + back)
      dalleBase = buildDallEPromptBase(options);
    }

    // ── Steps 5-8: Generate views sequentially for better control ─────────
    console.log(`[Jersey Generation] Generating FRONT view first...`);
    
    const baseSpec = `You are a professional sports apparel designer. Generate a photorealistic football jersey product mockup.

DESIGN SPEC (follow EXACTLY):
${designSpec}

CRITICAL REQUIREMENTS:
- Pure white background (#FFFFFF) on all views
- No shadows, no mannequin, no props
- Professional product photography quality
- Flat-lay overhead view
- Same lighting and fabric texture across all views`;

    // Generate FRONT view first
    const frontResponse = await openai.images.generate({
      model: "gpt-image-1",
      prompt: `${baseSpec}\n\nFRONT VIEW: Show the complete front of the football jersey. Display collar, both sleeves with patterns clearly visible, chest area with logos/sponsors. The LEFT sleeve is on the left side and RIGHT sleeve is on the right side when viewing from front.`,
      n: 1, size: "1024x1024", quality: "high",
    } as any);

    const frontB64 = (frontResponse.data?.[0] as any)?.b64_json;
    if (!frontB64) throw new Error("No image data received for front view.");

    // Analyze the generated front image to extract exact design details
    console.log(`[Jersey Generation] Analyzing front view for consistent back generation...`);
    const frontAnalysis = await analyzeFrontJerseyDesign(openai, frontB64);
    console.log(`[Jersey Generation] Front analysis: ${frontAnalysis.slice(0, 150)}...`);

    // Generate BACK view using front analysis
    console.log(`[Jersey Generation] Generating BACK view...`);
    const backResponse = await openai.images.generate({
      model: "gpt-image-1",
      prompt: `${baseSpec}\n\nBACK VIEW: Show the complete back of the SAME football jersey. Player name "${playerName || 'PLAYER'}" bold at top center. Number "${playerNumber || '00'}" large centered below. Use this exact design from the front: ${frontAnalysis}. Ensure colors, patterns, and fabric match perfectly.`,
      n: 1, size: "1024x1024", quality: "high",
    } as any);

    const backB64 = (backResponse.data?.[0] as any)?.b64_json;
    if (!backB64) throw new Error("No image data received for back view.");

    // Generate LEFT side view - be extremely explicit
    console.log(`[Jersey Generation] Generating LEFT SIDE view...`);
    const leftResponse = await openai.images.generate({
      model: "gpt-image-1",
      prompt: `${baseSpec}\n\nLEFT SIDE VIEW: Rotate the jersey to show ONLY the LEFT half. The LEFT sleeve must be centered and fully visible. The RIGHT sleeve must be completely hidden behind the jersey. This is the sleeve that appears on the LEFT side when viewing the front. Show exact same patterns and colors.`,
      n: 1, size: "1024x1024", quality: "high",
    } as any);

    const leftB64 = (leftResponse.data?.[0] as any)?.b64_json;
    if (!leftB64) throw new Error("No image data received for left view.");

    // Generate RIGHT side view - be extremely explicit
    console.log(`[Jersey Generation] Generating RIGHT SIDE view...`);
    const rightResponse = await openai.images.generate({
      model: "gpt-image-1",
      prompt: `${baseSpec}\n\nRIGHT SIDE VIEW: Rotate the jersey to show ONLY the RIGHT half. The RIGHT sleeve must be centered and fully visible. The LEFT sleeve must be completely hidden behind the jersey. This is the sleeve that appears on the RIGHT side when viewing the front. Show exact same patterns and colors.`,
      n: 1, size: "1024x1024", quality: "high",
    } as any);

    const rightB64 = (rightResponse.data?.[0] as any)?.b64_json;
    if (!rightB64) throw new Error("No image data received for right view.");

    // ── Step 9: Stitch 4 views into 2×2 grid using sharp ─────────────────
    console.log(`[Jersey Generation] Stitching 4 views into 2×2 grid...`);
    const resizeOpts = { fit: "contain" as const, background: { r: 255, g: 255, b: 255, alpha: 1 } };
    const [frontResized, backResized, leftResized, rightResized] = await Promise.all([
      sharp(Buffer.from(frontB64, "base64")).resize(1024, 1024, resizeOpts).toBuffer(),
      sharp(Buffer.from(backB64,  "base64")).resize(1024, 1024, resizeOpts).toBuffer(),
      sharp(Buffer.from(leftB64,  "base64")).resize(1024, 1024, resizeOpts).toBuffer(),
      sharp(Buffer.from(rightB64, "base64")).resize(1024, 1024, resizeOpts).toBuffer(),
    ]);

    // 2×2 grid: top-left=Front, top-right=Back, bottom-left=Left, bottom-right=Right
    const combinedBuffer = await sharp({
      create: { width: 2048, height: 2048, channels: 4, background: { r: 255, g: 255, b: 255, alpha: 1 } }
    })
      .composite([
        { input: frontResized, left: 0,    top: 0    },
        { input: backResized,  left: 1024, top: 0    },
        { input: leftResized,  left: 0,    top: 1024 },
        { input: rightResized, left: 1024, top: 1024 },
      ])
      .png()
      .toBuffer();

    const combinedBase64 = combinedBuffer.toString("base64");

    // ── Step 8: Upload to ImageKit ────────────────────────────────────────
    console.log(`[Jersey Generation] Uploading combined image to ImageKit...`);
    const timestamp = Date.now();
    const uploadResult = await imagekit.upload({
      file: combinedBase64,
      fileName: `jersey-combined-${preset || 'custom'}-${timestamp}.png`,
      folder: "/jersey-designs",
      tags: ["jersey", "combined-view", "gpt-image-1", preset || "custom"],
    });

    // ── Step 9: Save to cache ─────────────────────────────────────────────
    if (!fromCache) {
      saveToCache(options, designSpec, dalleBase);
    }

    console.log(`[Jersey Generation] Done! fromCache: ${fromCache}`);

    return {
      success: true,
      images: [uploadResult.url],
      prompt: designSpec,
      model: "gpt-image-1",
      preset: preset || null,
      sourceFilesAnalyzed: sourceFiles?.length || 0,
      fromCache,
    } as JerseyGenerationResult;

  } catch (err: any) {
    console.error("[Jersey Generation Error] status:", err?.status);
    console.error("[Jersey Generation Error] message:", err?.message);

    if (err?.status === 429 || err?.code === "rate_limit_exceeded" || err?.message?.includes("rate limit")) {
      const e = new Error(`OpenAI rate limit exceeded. Please try again in a minute.`);
      (e as any).status = 429;
      throw e;
    }
    if (err?.status === 401 || err?.message?.includes("Incorrect API key") || err?.message?.includes("Invalid API key")) {
      const e = new Error("Invalid OpenAI API key. Check OPENAI_API_KEY in your .env file.");
      (e as any).status = 401;
      throw e;
    }
    if (err?.message?.includes("ImageKit")) {
      throw new Error("Failed to save generated images to storage. Please try again.");
    }
    throw err;
  }
}

/**
 * Get all available jersey presets
 */
export function getJerseyPresets() {
  return Object.entries(JERSEY_PRESETS).map(([key, value]) => ({
    id: key,
    ...value
  }));
}
